apiVersion: v1
data:
  mapRoles: |
    - groups:  
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::265355210954:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1T3MHA1E4OU5V
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn : arn:aws:iam::265355210954:role/UdacityFlaskDeployCBKubectlRole 
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T14:32:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1506"
  uid: 65f1d830-352c-4216-9830-f7a4466eb411
